### ISSUE TITLE
1차 UI Mockup

### ISSUE THREAD

**Issue by skyoo2003** [itslaves/rentalgames-front#1]
### 내용

Login, Join, MyPage 화면을 구현하고 storybook 도 추가.
UI 형태를 잡고 같이 보는 것이 최우선 목표. 가짜 데이터를 사용하고 기능도 100% 동작하지 않아도 됨

### To-do List

- [x] `views/Login.vue`
- [x] `views/Join.vue` 
- [x] `views/MyPage.vue`

**Comment by skyoo2003** [comment]
스토리북 깃헙 페이지 만드는거 알아보기
- https://github.com/storybooks/storybook-deployer
